////Author: Seif Bassiouny
////Date: 16/9/2022
////Version: 1.5
////Module: ADC

#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

/*
OPTIONS:
ADC_Uint8_RIGHTADJUSTMENT - ADC_Uint8_LEFTADJUSTMENT
*/
#define ADC_Uint8_ADLAR				ADC_Uint8_LEFTADJUSTMENT
/*
OPTIONS:
ADC_Uint8_POLLING - ADC_Uint8_INTERRUPT
*/
#define ADC_Uint8_RECEIVING_MODE	ADC_Uint8_POLLING
/*
OPTIONS:
ADC_Uint8_AREF - ADC_Uint8_AVCC - ADC_Uint8_INTERNAL
*/
#define ADC_Uint8_VREF				ADC_Uint8_INTERNAL	
/*
OPTIONS:
ADC_Uint8_2_DIVFACTOR - ADC_Uint8_4_DIVFACTOR - ADC_Uint8_8_DIVFACTOR - ADC_Uint8_16_DIVFACTOR - ADC_Uint8_32_DIVFACTOR - ADC_Uint8_64_DIVFACTOR - ADC_Uint8_128_DIVFACTOR
*/
#define ADC_Uint8_PRESCALER			ADC_Uint8_32_DIVFACTOR
/*
OPTIONS:
ADC_Uint8_SINGLECONVERSION - ADC_Uint8_FREERUNNING - ADC_Uint8_AUTOTRIGGER
*/
#define ADC_Uint8_MODE				ADC_Uint8_SINGLECONVERSION


#endif // ADC_CONFIG_H_
