////Author: Seif Bassiouny
////Date: 21/9/2022
////Version: 1.6
////Module: TIMER1


#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

/*
OPTIONS:
TIMER0_Uint8_NORMAL - TIMER0_Uint8_CTC - TIMER0_Uint8_PWM_PHASE_CORRECT - TIMER0_Uint8_FAST_PWM
*/
//#define TIMER0_Uint8_MODE				TIMER0_Uint8_FAST_PWM
/*
OPTIONS: 
TIMER0_Uint8_SET - TIMER0_Uint8_CLEAR - TIMER0_Uint8_TOGGLE - TIMER0_Uint8_NORMAL_PORT
*/
//#define TIMER0_Uint8_OC0_MODE			TIMER0_Uint8_NON_INVERTING
/*
OPTIONS: 
TIMER0_Uint8_INTERNAL_CLOCK_1 - TIMER0_Uint8_INTERNAL_CLOCK_8 - TIMER0_Uint8_INTERNAL_CLOCK_64 - TIMER0_Uint8_INTERNAL_CLOCK_256 - TIMER0_Uint8_INTERNAL_CLOCK_1024 - 
TIMER0_Uint8_EXTERNAL_CLOCK_T0_FALLING_EDGE - TIMER0_Uint8_EXTERNAL_CLOCK_T0_RISING_EDGE - TIMER0_Uint8_NO_CLOCK_SOURCE
*/
//#define TIMER1_Uint8_CLOCK_SELECT		TIMER1_Uint8_INTERNAL_CLOCK_1

#endif // TIMER1_CONFIG_H_